### ISSUE TITLE
Debugger not functioning on Linux in VSCode

### ISSUE THREAD

**Issue by kaug-whis** [vshaxe/hashlink-debugger#120] opened 2023-05-04 20:22 UTC
**Symptoms:**  
With  
```json
{
  "name": "HashLink",
  "request": "launch",
  "type": "hl",
  "cwd": "${workspaceFolder}",
  "internalConsoleOptions":"openOnSessionStart",
  "preLaunchTask": "${defaultBuildTask}"
}
```  
App compiles, opens and runs, and debug controls (with pause, step, rebuild, stop) appear.   
However:
* No trace output or error information goes to the debug panel
  * Upon closing the app, all output appears in the debug panel at once
* Breakpoints trigger the debugger, but clicking 'continue' crashes VSCode and leaves a zombie `adapter.js` process which consumes a lot of CPU
* The 'pause' button is not functional 
* The 'restart' button recompiles but does not launch
* The 'stop' button closes the debugger without closing the program
  * Closing the program does correctly close the debugger as well, though

With a running `hl --debug 6112 out/hl/main.hl` in the VSCode terminal and
```json
{
    "name": "HashLink (attach)",
    "request": "attach",
    "port": 6112,
    "type": "hl",
    "cwd": "${workspaceFolder}",
}
```
The error `Failed to initialize debugger` appears, with options to dismiss the error or open `launch.json`.  
Perhaps interestingly, with `hl --debug 6112 --debug-wait out/hl/main.hl`, the app appears at the same time as the `Failed to initialize debugger` message, as if the debugger it had been waiting for had attached, but of course the debugger does not open.

**Software Versions:**  
* VSCode: `1.78.0` (Also replicated with prior version `1.77._`)  
* HashLink Debugger: `1.3.4` (Similar issues when built from latest git * source)  
* Haxe: `4.3.1`  
* HashLink: `1.13.0`  
* Heaps: `Git latest`  
* Linux flavor: `Ubuntu (Mint)`

**Notes:**  
* With the above configs/project, the debugger works as expected on Windows 11
* There is at least [one other person](https://community.haxe.org/t/vscode-hashlink-debugger-traces/3658/11) with a similar issue and no resolution in the thread
* There is also [this relatively recent comment](https://github.com/vshaxe/hashlink-debugger/issues/77#issuecomment-1264048060) on an older Linux issue which mentions the 'crash on step' behavior as well
* When using the extension built from git latest source, symptoms are similar except the app itself also fails to launch using the first of the two configs
* When triggering a breakpoint with the first method, everything seems to be working as intended for that moment; variables appear in inspector and show on hover

I would be very obliged if there are any hints at how to solve this or where best to begin investigating.

**Comment by ProfDiesel** [comment] 2024-01-13 21:45
Out of curiosity, what's the value of your `/proc/sys/kernel/yama/ptrace_scope` ?

**Comment by ProfDiesel** [comment] 2024-01-14 16:42
Set it to `0`. That would at least resolve the issue with attaching to a running process, and maybe some you have in launch mode.
(https://www.kernel.org/doc/Documentation/security/Yama.txt. Btw, you can make it permanent by editing `/etc/sysctl.d/10-ptrace.conf`)

**Comment by ProfDiesel** [comment] 2024-01-27 20:42
The call to `hld_Debugger.resume` seems to end up into https://github.com/vshaxe/hashlink-debugger/blob/master/hldebug-wrapper/src/debug.c#L295. Yet another failing call to `ptrace`.
If you try and attach a "standard" native debugger to the hashlink process, such as gdb. Can you break into the code (ctrl+C) resume (`cont`), etc ?

**Comment by ncannasse** [comment] 2024-02-16 07:44
Ping @yuxiaomao 😉

**Comment by acodervic** [comment] 2024-02-23 01:39
I have same problem in ubuntu20 .

**Comment by yuxiaomao** [comment] 2024-04-22 06:42
All listed point fixed in the version 1.4.9, with a message about ptrace_scope. Tested on my Ubuntu 22 VM with VSCode and a game project.
There is a hack however https://github.com/vshaxe/hashlink-debugger/commit/6e7d3794c94704d71314a19457628dedb77f1eee (but without it the code would be more complexe - semaphore and thread - that I didn't managed to get it works yet), so please tell me if the "display hl output in nearly realtime" is broken on your system, and provide details about your system's configuration.

**Comment by yuxiaomao** [comment] 2024-04-24 06:45
@kaug-whis Glad to know that my fix works (mostly) for you! "Pause" works on Windows 11 and on Ubuntu 22 for me.
It's a a little bit strange because setting breakpoints on runtime will actually pause and resume hl.
I would like know your OS,  if you reproduce with a simple project (e.g. sleep inside a loop) and if you have more information when activate "verbose" mode in hashlink-debugger extension settings (`"hldebug.verbose" : true`) - normally it have "pause request" then "stopped on <tid>".

**Comment by yuxiaomao** [comment] 2024-04-25 06:19
@kaug-whis thank you for the information! I'll check when I have time

**Comment by yuxiaomao** [comment] 2024-04-25 12:08
Re-Open just in case that I forgot

**Closed** 2024-04-29 09:31 UTC
