### ISSUE TITLE
Windows: Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [vshaxe/hashlink-debugger#38] opened 2019-01-27 17:04 UTC
A new error with the latest VSCode version. Run on windows:

```
Debug adapter process has terminated unexpectedly (Error: read error Error: read error at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:387:585) at emitOne (events.js:121:20) at Socket.emit (events.js:211:7) at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12))
```

**Comment by ncannasse** [comment] 2019-01-28 14:59
Which VSCode version are you using? I don't have any problem with 1.30.2

**Comment by 4lph4-Ph4un** [comment] 2019-01-29 09:05
Huh, that's strange. I'm using 1.30.2 too. I wonder if I have goofed up my configs. They are like this:

launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [     
    {
      "name":    "HashLink",
      "request": "launch",
      "type":    "hl",
      "hxml":    "compile.hxml",
      "cwd":     "${workspaceRoot}",
      "preLaunchTask": {
        "type" : "haxe",
	"args" : "active configuration"
      }
    }
  ]
}
```

tasks.json:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "haxe",
      "args": "active configuration",
      "problemMatcher": [
        "$haxe-absolute",
        "$haxe",
        "$haxe-error",
        "$haxe-trace"
      ],
      "group": {
        "kind":      "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by ncannasse** [comment] 2019-01-29 09:09
Try upgrading your HashLink Debugger plugin maybe ?

Le mar. 29 janv. 2019 10:05, 4lph4-Ph4un <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment] 2019-01-31 11:07
No it's the correct version... No idea why it crashes sadly :'(

**Comment by Gama11** [comment] 2019-02-06 19:03
I have the same issue. The Extensions output channel has this error:

```
c:\Users\Jens\.vscode\extensions\hashlink-debugger\node_modules\bindings\bindings.js:119
        throw e;
        ^
Error: A dynamic link library (DLL) initialization routine failed.

\\?\c:\Users\Jens\.vscode\extensions\hashlink-debugger\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (c:\Users\Jens\.vscode\extensions\hashlink-debugger\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (c:\Users\Jens\.vscode\extensions\hashlink-debugger\node_modules\ref\lib\ref.js:5:47)c:\Users\Jens\.vscode\extensions\hashlink-debugger\node_modules\bindings\bindings.js:119
```

**Comment by Gama11** [comment] 2019-02-06 19:16
Oh, it seems that was due to me not using `make deps` as instructed... But initially I had the same "Debug adapter process has terminated unexpectedly" error with the marketplace release, whereas that now suddenly worked..

(and now it doesn't again because of the new VSCode release)

**Comment by 4lph4-Ph4un** [comment] 2019-02-07 03:29
Whoa, I reinstalled my VS Code just to make sure there's no crap on my environment. Now attempting to run the debugger resulted in this:

![eh](https://user-images.githubusercontent.com/25401310/52388881-35a6d680-2a99-11e9-84c1-1f0808e959ab.png)

The confusion intensifies!

**Comment by Gama11** [comment] 2019-02-07 17:30
@4lph4-Ph4un Does it work if you try with VSCode 1.31.0 and 0.5.2 of hashlink-debugger (which was just released)? That combination works for me.

Have you made sure to try with an empty hello-world project?

**Comment by 4lph4-Ph4un** [comment] 2019-02-23 19:01
Hi! Sorry for the late reply. Unfortunately I get the same overflow -message even with an empty hello-world -project. :/

**Comment by ncannasse** [comment] 2019-02-27 04:45
Are you using 64 bit vscode ?

Le sam. 23 févr. 2019 20:01, 4lph4-Ph4un <notifications@github.com> a
écrit :

**Comment by 4lph4-Ph4un** [comment] 2019-02-27 12:04
@ncannasse, yup! Using 64bit version.

**Comment by ncannasse** [comment] 2019-03-03 10:27
Duplicate of #46

**Closed by ncannasse** 2019-03-03 10:27 UTC

**Comment by ncannasse** [comment] 2019-03-04 13:11
Could you update to hashlink debugger 0.6.0 which I just released and try again?

**Comment by 4lph4-Ph4un** [comment] 2019-03-05 09:24
@ncannasse, IT WORKS!!! You have no idea how happy I am now! 😄
